/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedMainRouteRouteImport } from './routes/_authenticated/_main/route'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as ImageProxySplatRouteImport } from './routes/image-proxy/$'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as VerifyIndexRouteImport } from './routes/verify/index'
import { Route as AuthenticatedMainIndexRouteImport } from './routes/_authenticated/_main/index'
import { Route as AuthenticatedMainAdminRouteRouteImport } from './routes/_authenticated/_main/admin/route'
import { Route as AuthenticatedMainSettingsRouteRouteImport } from './routes/_authenticated/_main/settings/route'
import { Route as AuthenticatedCheckoutReturnIndexRouteImport } from './routes/_authenticated/checkout-return/index'
import { Route as AuthenticatedChoosePlanIndexRouteImport } from './routes/_authenticated/choose-plan/index'
import { Route as AuthenticatedNewOrganizationIndexRouteImport } from './routes/_authenticated/new-organization/index'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedMainOrganizationSlugIndexRouteImport } from './routes/_authenticated/_main/$organizationSlug/index'
import { Route as AuthenticatedMainOrganizationSlugSettingsRouteRouteImport } from './routes/_authenticated/_main/$organizationSlug/settings/route'
import { Route as AuthenticatedMainAdminIndexRouteImport } from './routes/_authenticated/_main/admin/index'
import { Route as AuthenticatedMainChatbotIndexRouteImport } from './routes/_authenticated/_main/chatbot/index'
import { Route as AuthenticatedMainSettingsIndexRouteImport } from './routes/_authenticated/_main/settings/index'
import { Route as AuthenticatedOrganizationInvitationInvitationIdIndexRouteImport } from './routes/_authenticated/organization-invitation/$invitationId/index'
import { Route as AuthenticatedMainOrganizationSlugSettingsIndexRouteImport } from './routes/_authenticated/_main/$organizationSlug/settings/index'
import { Route as AuthenticatedMainAdminOrganizationsIndexRouteImport } from './routes/_authenticated/_main/admin/organizations/index'
import { Route as AuthenticatedMainAdminUsersIndexRouteImport } from './routes/_authenticated/_main/admin/users/index'
import { Route as AuthenticatedMainSettingsBillingIndexRouteImport } from './routes/_authenticated/_main/settings/billing/index'
import { Route as AuthenticatedMainSettingsGeneralIndexRouteImport } from './routes/_authenticated/_main/settings/general/index'
import { Route as AuthenticatedMainSettingsNotificationsIndexRouteImport } from './routes/_authenticated/_main/settings/notifications/index'
import { Route as AuthenticatedMainSettingsSecurityIndexRouteImport } from './routes/_authenticated/_main/settings/security/index'
import { Route as AuthenticatedMainOrganizationSlugSettingsBillingIndexRouteImport } from './routes/_authenticated/_main/$organizationSlug/settings/billing/index'
import { Route as AuthenticatedMainOrganizationSlugSettingsGeneralIndexRouteImport } from './routes/_authenticated/_main/$organizationSlug/settings/general/index'
import { Route as AuthenticatedMainOrganizationSlugSettingsMembersIndexRouteImport } from './routes/_authenticated/_main/$organizationSlug/settings/members/index'
import { Route as AuthenticatedMainAdminOrganizationsOrganizationIdIndexRouteImport } from './routes/_authenticated/_main/admin/organizations/$organizationId/index'
import { Route as AuthenticatedMainAdminOrganizationsNewIndexRouteImport } from './routes/_authenticated/_main/admin/organizations/new/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMainRouteRoute = AuthenticatedMainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageProxySplatRoute = ImageProxySplatRouteImport.update({
  id: '/image-proxy/$',
  path: '/image-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMainIndexRoute = AuthenticatedMainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMainRouteRoute,
} as any)
const AuthenticatedMainAdminRouteRoute =
  AuthenticatedMainAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedMainRouteRoute,
  } as any)
const AuthenticatedMainSettingsRouteRoute =
  AuthenticatedMainSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMainRouteRoute,
  } as any)
const AuthenticatedCheckoutReturnIndexRoute =
  AuthenticatedCheckoutReturnIndexRouteImport.update({
    id: '/checkout-return/',
    path: '/checkout-return/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChoosePlanIndexRoute =
  AuthenticatedChoosePlanIndexRouteImport.update({
    id: '/choose-plan/',
    path: '/choose-plan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNewOrganizationIndexRoute =
  AuthenticatedNewOrganizationIndexRouteImport.update({
    id: '/new-organization/',
    path: '/new-organization/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMainOrganizationSlugIndexRoute =
  AuthenticatedMainOrganizationSlugIndexRouteImport.update({
    id: '/$organizationSlug/',
    path: '/$organizationSlug/',
    getParentRoute: () => AuthenticatedMainRouteRoute,
  } as any)
const AuthenticatedMainOrganizationSlugSettingsRouteRoute =
  AuthenticatedMainOrganizationSlugSettingsRouteRouteImport.update({
    id: '/$organizationSlug/settings',
    path: '/$organizationSlug/settings',
    getParentRoute: () => AuthenticatedMainRouteRoute,
  } as any)
const AuthenticatedMainAdminIndexRoute =
  AuthenticatedMainAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMainAdminRouteRoute,
  } as any)
const AuthenticatedMainChatbotIndexRoute =
  AuthenticatedMainChatbotIndexRouteImport.update({
    id: '/chatbot/',
    path: '/chatbot/',
    getParentRoute: () => AuthenticatedMainRouteRoute,
  } as any)
const AuthenticatedMainSettingsIndexRoute =
  AuthenticatedMainSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMainSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationInvitationInvitationIdIndexRoute =
  AuthenticatedOrganizationInvitationInvitationIdIndexRouteImport.update({
    id: '/organization-invitation/$invitationId/',
    path: '/organization-invitation/$invitationId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMainOrganizationSlugSettingsIndexRoute =
  AuthenticatedMainOrganizationSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMainOrganizationSlugSettingsRouteRoute,
  } as any)
const AuthenticatedMainAdminOrganizationsIndexRoute =
  AuthenticatedMainAdminOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedMainAdminRouteRoute,
  } as any)
const AuthenticatedMainAdminUsersIndexRoute =
  AuthenticatedMainAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedMainAdminRouteRoute,
  } as any)
const AuthenticatedMainSettingsBillingIndexRoute =
  AuthenticatedMainSettingsBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedMainSettingsRouteRoute,
  } as any)
const AuthenticatedMainSettingsGeneralIndexRoute =
  AuthenticatedMainSettingsGeneralIndexRouteImport.update({
    id: '/general/',
    path: '/general/',
    getParentRoute: () => AuthenticatedMainSettingsRouteRoute,
  } as any)
const AuthenticatedMainSettingsNotificationsIndexRoute =
  AuthenticatedMainSettingsNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedMainSettingsRouteRoute,
  } as any)
const AuthenticatedMainSettingsSecurityIndexRoute =
  AuthenticatedMainSettingsSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => AuthenticatedMainSettingsRouteRoute,
  } as any)
const AuthenticatedMainOrganizationSlugSettingsBillingIndexRoute =
  AuthenticatedMainOrganizationSlugSettingsBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedMainOrganizationSlugSettingsRouteRoute,
  } as any)
const AuthenticatedMainOrganizationSlugSettingsGeneralIndexRoute =
  AuthenticatedMainOrganizationSlugSettingsGeneralIndexRouteImport.update({
    id: '/general/',
    path: '/general/',
    getParentRoute: () => AuthenticatedMainOrganizationSlugSettingsRouteRoute,
  } as any)
const AuthenticatedMainOrganizationSlugSettingsMembersIndexRoute =
  AuthenticatedMainOrganizationSlugSettingsMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedMainOrganizationSlugSettingsRouteRoute,
  } as any)
const AuthenticatedMainAdminOrganizationsOrganizationIdIndexRoute =
  AuthenticatedMainAdminOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/organizations/$organizationId/',
    path: '/organizations/$organizationId/',
    getParentRoute: () => AuthenticatedMainAdminRouteRoute,
  } as any)
const AuthenticatedMainAdminOrganizationsNewIndexRoute =
  AuthenticatedMainAdminOrganizationsNewIndexRouteImport.update({
    id: '/organizations/new/',
    path: '/organizations/new/',
    getParentRoute: () => AuthenticatedMainAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedMainIndexRoute
  '/api/$': typeof ApiSplatRoute
  '/image-proxy/$': typeof ImageProxySplatRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/admin': typeof AuthenticatedMainAdminRouteRouteWithChildren
  '/settings': typeof AuthenticatedMainSettingsRouteRouteWithChildren
  '/checkout-return/': typeof AuthenticatedCheckoutReturnIndexRoute
  '/choose-plan/': typeof AuthenticatedChoosePlanIndexRoute
  '/new-organization/': typeof AuthenticatedNewOrganizationIndexRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/$organizationSlug/settings': typeof AuthenticatedMainOrganizationSlugSettingsRouteRouteWithChildren
  '/$organizationSlug/': typeof AuthenticatedMainOrganizationSlugIndexRoute
  '/admin/': typeof AuthenticatedMainAdminIndexRoute
  '/chatbot/': typeof AuthenticatedMainChatbotIndexRoute
  '/settings/': typeof AuthenticatedMainSettingsIndexRoute
  '/organization-invitation/$invitationId/': typeof AuthenticatedOrganizationInvitationInvitationIdIndexRoute
  '/$organizationSlug/settings/': typeof AuthenticatedMainOrganizationSlugSettingsIndexRoute
  '/admin/organizations/': typeof AuthenticatedMainAdminOrganizationsIndexRoute
  '/admin/users/': typeof AuthenticatedMainAdminUsersIndexRoute
  '/settings/billing/': typeof AuthenticatedMainSettingsBillingIndexRoute
  '/settings/general/': typeof AuthenticatedMainSettingsGeneralIndexRoute
  '/settings/notifications/': typeof AuthenticatedMainSettingsNotificationsIndexRoute
  '/settings/security/': typeof AuthenticatedMainSettingsSecurityIndexRoute
  '/$organizationSlug/settings/billing/': typeof AuthenticatedMainOrganizationSlugSettingsBillingIndexRoute
  '/$organizationSlug/settings/general/': typeof AuthenticatedMainOrganizationSlugSettingsGeneralIndexRoute
  '/$organizationSlug/settings/members/': typeof AuthenticatedMainOrganizationSlugSettingsMembersIndexRoute
  '/admin/organizations/$organizationId/': typeof AuthenticatedMainAdminOrganizationsOrganizationIdIndexRoute
  '/admin/organizations/new/': typeof AuthenticatedMainAdminOrganizationsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedMainIndexRoute
  '/api/$': typeof ApiSplatRoute
  '/image-proxy/$': typeof ImageProxySplatRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/signup': typeof SignupIndexRoute
  '/verify': typeof VerifyIndexRoute
  '/checkout-return': typeof AuthenticatedCheckoutReturnIndexRoute
  '/choose-plan': typeof AuthenticatedChoosePlanIndexRoute
  '/new-organization': typeof AuthenticatedNewOrganizationIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/$organizationSlug': typeof AuthenticatedMainOrganizationSlugIndexRoute
  '/admin': typeof AuthenticatedMainAdminIndexRoute
  '/chatbot': typeof AuthenticatedMainChatbotIndexRoute
  '/settings': typeof AuthenticatedMainSettingsIndexRoute
  '/organization-invitation/$invitationId': typeof AuthenticatedOrganizationInvitationInvitationIdIndexRoute
  '/$organizationSlug/settings': typeof AuthenticatedMainOrganizationSlugSettingsIndexRoute
  '/admin/organizations': typeof AuthenticatedMainAdminOrganizationsIndexRoute
  '/admin/users': typeof AuthenticatedMainAdminUsersIndexRoute
  '/settings/billing': typeof AuthenticatedMainSettingsBillingIndexRoute
  '/settings/general': typeof AuthenticatedMainSettingsGeneralIndexRoute
  '/settings/notifications': typeof AuthenticatedMainSettingsNotificationsIndexRoute
  '/settings/security': typeof AuthenticatedMainSettingsSecurityIndexRoute
  '/$organizationSlug/settings/billing': typeof AuthenticatedMainOrganizationSlugSettingsBillingIndexRoute
  '/$organizationSlug/settings/general': typeof AuthenticatedMainOrganizationSlugSettingsGeneralIndexRoute
  '/$organizationSlug/settings/members': typeof AuthenticatedMainOrganizationSlugSettingsMembersIndexRoute
  '/admin/organizations/$organizationId': typeof AuthenticatedMainAdminOrganizationsOrganizationIdIndexRoute
  '/admin/organizations/new': typeof AuthenticatedMainAdminOrganizationsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_main': typeof AuthenticatedMainRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/image-proxy/$': typeof ImageProxySplatRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/verify/': typeof VerifyIndexRoute
  '/_authenticated/_main/admin': typeof AuthenticatedMainAdminRouteRouteWithChildren
  '/_authenticated/_main/settings': typeof AuthenticatedMainSettingsRouteRouteWithChildren
  '/_authenticated/_main/': typeof AuthenticatedMainIndexRoute
  '/_authenticated/checkout-return/': typeof AuthenticatedCheckoutReturnIndexRoute
  '/_authenticated/choose-plan/': typeof AuthenticatedChoosePlanIndexRoute
  '/_authenticated/new-organization/': typeof AuthenticatedNewOrganizationIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/_main/$organizationSlug/settings': typeof AuthenticatedMainOrganizationSlugSettingsRouteRouteWithChildren
  '/_authenticated/_main/$organizationSlug/': typeof AuthenticatedMainOrganizationSlugIndexRoute
  '/_authenticated/_main/admin/': typeof AuthenticatedMainAdminIndexRoute
  '/_authenticated/_main/chatbot/': typeof AuthenticatedMainChatbotIndexRoute
  '/_authenticated/_main/settings/': typeof AuthenticatedMainSettingsIndexRoute
  '/_authenticated/organization-invitation/$invitationId/': typeof AuthenticatedOrganizationInvitationInvitationIdIndexRoute
  '/_authenticated/_main/$organizationSlug/settings/': typeof AuthenticatedMainOrganizationSlugSettingsIndexRoute
  '/_authenticated/_main/admin/organizations/': typeof AuthenticatedMainAdminOrganizationsIndexRoute
  '/_authenticated/_main/admin/users/': typeof AuthenticatedMainAdminUsersIndexRoute
  '/_authenticated/_main/settings/billing/': typeof AuthenticatedMainSettingsBillingIndexRoute
  '/_authenticated/_main/settings/general/': typeof AuthenticatedMainSettingsGeneralIndexRoute
  '/_authenticated/_main/settings/notifications/': typeof AuthenticatedMainSettingsNotificationsIndexRoute
  '/_authenticated/_main/settings/security/': typeof AuthenticatedMainSettingsSecurityIndexRoute
  '/_authenticated/_main/$organizationSlug/settings/billing/': typeof AuthenticatedMainOrganizationSlugSettingsBillingIndexRoute
  '/_authenticated/_main/$organizationSlug/settings/general/': typeof AuthenticatedMainOrganizationSlugSettingsGeneralIndexRoute
  '/_authenticated/_main/$organizationSlug/settings/members/': typeof AuthenticatedMainOrganizationSlugSettingsMembersIndexRoute
  '/_authenticated/_main/admin/organizations/$organizationId/': typeof AuthenticatedMainAdminOrganizationsOrganizationIdIndexRoute
  '/_authenticated/_main/admin/organizations/new/': typeof AuthenticatedMainAdminOrganizationsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/$'
    | '/image-proxy/$'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/signup/'
    | '/verify/'
    | '/admin'
    | '/settings'
    | '/checkout-return/'
    | '/choose-plan/'
    | '/new-organization/'
    | '/onboarding/'
    | '/$organizationSlug/settings'
    | '/$organizationSlug/'
    | '/admin/'
    | '/chatbot/'
    | '/settings/'
    | '/organization-invitation/$invitationId/'
    | '/$organizationSlug/settings/'
    | '/admin/organizations/'
    | '/admin/users/'
    | '/settings/billing/'
    | '/settings/general/'
    | '/settings/notifications/'
    | '/settings/security/'
    | '/$organizationSlug/settings/billing/'
    | '/$organizationSlug/settings/general/'
    | '/$organizationSlug/settings/members/'
    | '/admin/organizations/$organizationId/'
    | '/admin/organizations/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/$'
    | '/image-proxy/$'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/checkout-return'
    | '/choose-plan'
    | '/new-organization'
    | '/onboarding'
    | '/$organizationSlug'
    | '/admin'
    | '/chatbot'
    | '/settings'
    | '/organization-invitation/$invitationId'
    | '/$organizationSlug/settings'
    | '/admin/organizations'
    | '/admin/users'
    | '/settings/billing'
    | '/settings/general'
    | '/settings/notifications'
    | '/settings/security'
    | '/$organizationSlug/settings/billing'
    | '/$organizationSlug/settings/general'
    | '/$organizationSlug/settings/members'
    | '/admin/organizations/$organizationId'
    | '/admin/organizations/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_main'
    | '/api/$'
    | '/image-proxy/$'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/signup/'
    | '/verify/'
    | '/_authenticated/_main/admin'
    | '/_authenticated/_main/settings'
    | '/_authenticated/_main/'
    | '/_authenticated/checkout-return/'
    | '/_authenticated/choose-plan/'
    | '/_authenticated/new-organization/'
    | '/_authenticated/onboarding/'
    | '/_authenticated/_main/$organizationSlug/settings'
    | '/_authenticated/_main/$organizationSlug/'
    | '/_authenticated/_main/admin/'
    | '/_authenticated/_main/chatbot/'
    | '/_authenticated/_main/settings/'
    | '/_authenticated/organization-invitation/$invitationId/'
    | '/_authenticated/_main/$organizationSlug/settings/'
    | '/_authenticated/_main/admin/organizations/'
    | '/_authenticated/_main/admin/users/'
    | '/_authenticated/_main/settings/billing/'
    | '/_authenticated/_main/settings/general/'
    | '/_authenticated/_main/settings/notifications/'
    | '/_authenticated/_main/settings/security/'
    | '/_authenticated/_main/$organizationSlug/settings/billing/'
    | '/_authenticated/_main/$organizationSlug/settings/general/'
    | '/_authenticated/_main/$organizationSlug/settings/members/'
    | '/_authenticated/_main/admin/organizations/$organizationId/'
    | '/_authenticated/_main/admin/organizations/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ImageProxySplatRoute: typeof ImageProxySplatRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_main': {
      id: '/_authenticated/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedMainRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-proxy/$': {
      id: '/image-proxy/$'
      path: '/image-proxy/$'
      fullPath: '/image-proxy/$'
      preLoaderRoute: typeof ImageProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_main/': {
      id: '/_authenticated/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedMainIndexRouteImport
      parentRoute: typeof AuthenticatedMainRouteRoute
    }
    '/_authenticated/_main/admin': {
      id: '/_authenticated/_main/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedMainAdminRouteRouteImport
      parentRoute: typeof AuthenticatedMainRouteRoute
    }
    '/_authenticated/_main/settings': {
      id: '/_authenticated/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedMainSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedMainRouteRoute
    }
    '/_authenticated/checkout-return/': {
      id: '/_authenticated/checkout-return/'
      path: '/checkout-return'
      fullPath: '/checkout-return/'
      preLoaderRoute: typeof AuthenticatedCheckoutReturnIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/choose-plan/': {
      id: '/_authenticated/choose-plan/'
      path: '/choose-plan'
      fullPath: '/choose-plan/'
      preLoaderRoute: typeof AuthenticatedChoosePlanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-organization/': {
      id: '/_authenticated/new-organization/'
      path: '/new-organization'
      fullPath: '/new-organization/'
      preLoaderRoute: typeof AuthenticatedNewOrganizationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_main/$organizationSlug/': {
      id: '/_authenticated/_main/$organizationSlug/'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof AuthenticatedMainOrganizationSlugIndexRouteImport
      parentRoute: typeof AuthenticatedMainRouteRoute
    }
    '/_authenticated/_main/$organizationSlug/settings': {
      id: '/_authenticated/_main/$organizationSlug/settings'
      path: '/$organizationSlug/settings'
      fullPath: '/$organizationSlug/settings'
      preLoaderRoute: typeof AuthenticatedMainOrganizationSlugSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedMainRouteRoute
    }
    '/_authenticated/_main/admin/': {
      id: '/_authenticated/_main/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedMainAdminIndexRouteImport
      parentRoute: typeof AuthenticatedMainAdminRouteRoute
    }
    '/_authenticated/_main/chatbot/': {
      id: '/_authenticated/_main/chatbot/'
      path: '/chatbot'
      fullPath: '/chatbot/'
      preLoaderRoute: typeof AuthenticatedMainChatbotIndexRouteImport
      parentRoute: typeof AuthenticatedMainRouteRoute
    }
    '/_authenticated/_main/settings/': {
      id: '/_authenticated/_main/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedMainSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedMainSettingsRouteRoute
    }
    '/_authenticated/organization-invitation/$invitationId/': {
      id: '/_authenticated/organization-invitation/$invitationId/'
      path: '/organization-invitation/$invitationId'
      fullPath: '/organization-invitation/$invitationId/'
      preLoaderRoute: typeof AuthenticatedOrganizationInvitationInvitationIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_main/$organizationSlug/settings/': {
      id: '/_authenticated/_main/$organizationSlug/settings/'
      path: '/'
      fullPath: '/$organizationSlug/settings/'
      preLoaderRoute: typeof AuthenticatedMainOrganizationSlugSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedMainOrganizationSlugSettingsRouteRoute
    }
    '/_authenticated/_main/admin/organizations/': {
      id: '/_authenticated/_main/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AuthenticatedMainAdminOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedMainAdminRouteRoute
    }
    '/_authenticated/_main/admin/users/': {
      id: '/_authenticated/_main/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedMainAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedMainAdminRouteRoute
    }
    '/_authenticated/_main/settings/billing/': {
      id: '/_authenticated/_main/settings/billing/'
      path: '/billing'
      fullPath: '/settings/billing/'
      preLoaderRoute: typeof AuthenticatedMainSettingsBillingIndexRouteImport
      parentRoute: typeof AuthenticatedMainSettingsRouteRoute
    }
    '/_authenticated/_main/settings/general/': {
      id: '/_authenticated/_main/settings/general/'
      path: '/general'
      fullPath: '/settings/general/'
      preLoaderRoute: typeof AuthenticatedMainSettingsGeneralIndexRouteImport
      parentRoute: typeof AuthenticatedMainSettingsRouteRoute
    }
    '/_authenticated/_main/settings/notifications/': {
      id: '/_authenticated/_main/settings/notifications/'
      path: '/notifications'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof AuthenticatedMainSettingsNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedMainSettingsRouteRoute
    }
    '/_authenticated/_main/settings/security/': {
      id: '/_authenticated/_main/settings/security/'
      path: '/security'
      fullPath: '/settings/security/'
      preLoaderRoute: typeof AuthenticatedMainSettingsSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedMainSettingsRouteRoute
    }
    '/_authenticated/_main/$organizationSlug/settings/billing/': {
      id: '/_authenticated/_main/$organizationSlug/settings/billing/'
      path: '/billing'
      fullPath: '/$organizationSlug/settings/billing/'
      preLoaderRoute: typeof AuthenticatedMainOrganizationSlugSettingsBillingIndexRouteImport
      parentRoute: typeof AuthenticatedMainOrganizationSlugSettingsRouteRoute
    }
    '/_authenticated/_main/$organizationSlug/settings/general/': {
      id: '/_authenticated/_main/$organizationSlug/settings/general/'
      path: '/general'
      fullPath: '/$organizationSlug/settings/general/'
      preLoaderRoute: typeof AuthenticatedMainOrganizationSlugSettingsGeneralIndexRouteImport
      parentRoute: typeof AuthenticatedMainOrganizationSlugSettingsRouteRoute
    }
    '/_authenticated/_main/$organizationSlug/settings/members/': {
      id: '/_authenticated/_main/$organizationSlug/settings/members/'
      path: '/members'
      fullPath: '/$organizationSlug/settings/members/'
      preLoaderRoute: typeof AuthenticatedMainOrganizationSlugSettingsMembersIndexRouteImport
      parentRoute: typeof AuthenticatedMainOrganizationSlugSettingsRouteRoute
    }
    '/_authenticated/_main/admin/organizations/$organizationId/': {
      id: '/_authenticated/_main/admin/organizations/$organizationId/'
      path: '/organizations/$organizationId'
      fullPath: '/admin/organizations/$organizationId/'
      preLoaderRoute: typeof AuthenticatedMainAdminOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof AuthenticatedMainAdminRouteRoute
    }
    '/_authenticated/_main/admin/organizations/new/': {
      id: '/_authenticated/_main/admin/organizations/new/'
      path: '/organizations/new'
      fullPath: '/admin/organizations/new/'
      preLoaderRoute: typeof AuthenticatedMainAdminOrganizationsNewIndexRouteImport
      parentRoute: typeof AuthenticatedMainAdminRouteRoute
    }
  }
}

interface AuthenticatedMainAdminRouteRouteChildren {
  AuthenticatedMainAdminIndexRoute: typeof AuthenticatedMainAdminIndexRoute
  AuthenticatedMainAdminOrganizationsIndexRoute: typeof AuthenticatedMainAdminOrganizationsIndexRoute
  AuthenticatedMainAdminUsersIndexRoute: typeof AuthenticatedMainAdminUsersIndexRoute
  AuthenticatedMainAdminOrganizationsOrganizationIdIndexRoute: typeof AuthenticatedMainAdminOrganizationsOrganizationIdIndexRoute
  AuthenticatedMainAdminOrganizationsNewIndexRoute: typeof AuthenticatedMainAdminOrganizationsNewIndexRoute
}

const AuthenticatedMainAdminRouteRouteChildren: AuthenticatedMainAdminRouteRouteChildren =
  {
    AuthenticatedMainAdminIndexRoute: AuthenticatedMainAdminIndexRoute,
    AuthenticatedMainAdminOrganizationsIndexRoute:
      AuthenticatedMainAdminOrganizationsIndexRoute,
    AuthenticatedMainAdminUsersIndexRoute:
      AuthenticatedMainAdminUsersIndexRoute,
    AuthenticatedMainAdminOrganizationsOrganizationIdIndexRoute:
      AuthenticatedMainAdminOrganizationsOrganizationIdIndexRoute,
    AuthenticatedMainAdminOrganizationsNewIndexRoute:
      AuthenticatedMainAdminOrganizationsNewIndexRoute,
  }

const AuthenticatedMainAdminRouteRouteWithChildren =
  AuthenticatedMainAdminRouteRoute._addFileChildren(
    AuthenticatedMainAdminRouteRouteChildren,
  )

interface AuthenticatedMainSettingsRouteRouteChildren {
  AuthenticatedMainSettingsIndexRoute: typeof AuthenticatedMainSettingsIndexRoute
  AuthenticatedMainSettingsBillingIndexRoute: typeof AuthenticatedMainSettingsBillingIndexRoute
  AuthenticatedMainSettingsGeneralIndexRoute: typeof AuthenticatedMainSettingsGeneralIndexRoute
  AuthenticatedMainSettingsNotificationsIndexRoute: typeof AuthenticatedMainSettingsNotificationsIndexRoute
  AuthenticatedMainSettingsSecurityIndexRoute: typeof AuthenticatedMainSettingsSecurityIndexRoute
}

const AuthenticatedMainSettingsRouteRouteChildren: AuthenticatedMainSettingsRouteRouteChildren =
  {
    AuthenticatedMainSettingsIndexRoute: AuthenticatedMainSettingsIndexRoute,
    AuthenticatedMainSettingsBillingIndexRoute:
      AuthenticatedMainSettingsBillingIndexRoute,
    AuthenticatedMainSettingsGeneralIndexRoute:
      AuthenticatedMainSettingsGeneralIndexRoute,
    AuthenticatedMainSettingsNotificationsIndexRoute:
      AuthenticatedMainSettingsNotificationsIndexRoute,
    AuthenticatedMainSettingsSecurityIndexRoute:
      AuthenticatedMainSettingsSecurityIndexRoute,
  }

const AuthenticatedMainSettingsRouteRouteWithChildren =
  AuthenticatedMainSettingsRouteRoute._addFileChildren(
    AuthenticatedMainSettingsRouteRouteChildren,
  )

interface AuthenticatedMainOrganizationSlugSettingsRouteRouteChildren {
  AuthenticatedMainOrganizationSlugSettingsIndexRoute: typeof AuthenticatedMainOrganizationSlugSettingsIndexRoute
  AuthenticatedMainOrganizationSlugSettingsBillingIndexRoute: typeof AuthenticatedMainOrganizationSlugSettingsBillingIndexRoute
  AuthenticatedMainOrganizationSlugSettingsGeneralIndexRoute: typeof AuthenticatedMainOrganizationSlugSettingsGeneralIndexRoute
  AuthenticatedMainOrganizationSlugSettingsMembersIndexRoute: typeof AuthenticatedMainOrganizationSlugSettingsMembersIndexRoute
}

const AuthenticatedMainOrganizationSlugSettingsRouteRouteChildren: AuthenticatedMainOrganizationSlugSettingsRouteRouteChildren =
  {
    AuthenticatedMainOrganizationSlugSettingsIndexRoute:
      AuthenticatedMainOrganizationSlugSettingsIndexRoute,
    AuthenticatedMainOrganizationSlugSettingsBillingIndexRoute:
      AuthenticatedMainOrganizationSlugSettingsBillingIndexRoute,
    AuthenticatedMainOrganizationSlugSettingsGeneralIndexRoute:
      AuthenticatedMainOrganizationSlugSettingsGeneralIndexRoute,
    AuthenticatedMainOrganizationSlugSettingsMembersIndexRoute:
      AuthenticatedMainOrganizationSlugSettingsMembersIndexRoute,
  }

const AuthenticatedMainOrganizationSlugSettingsRouteRouteWithChildren =
  AuthenticatedMainOrganizationSlugSettingsRouteRoute._addFileChildren(
    AuthenticatedMainOrganizationSlugSettingsRouteRouteChildren,
  )

interface AuthenticatedMainRouteRouteChildren {
  AuthenticatedMainAdminRouteRoute: typeof AuthenticatedMainAdminRouteRouteWithChildren
  AuthenticatedMainSettingsRouteRoute: typeof AuthenticatedMainSettingsRouteRouteWithChildren
  AuthenticatedMainIndexRoute: typeof AuthenticatedMainIndexRoute
  AuthenticatedMainOrganizationSlugSettingsRouteRoute: typeof AuthenticatedMainOrganizationSlugSettingsRouteRouteWithChildren
  AuthenticatedMainOrganizationSlugIndexRoute: typeof AuthenticatedMainOrganizationSlugIndexRoute
  AuthenticatedMainChatbotIndexRoute: typeof AuthenticatedMainChatbotIndexRoute
}

const AuthenticatedMainRouteRouteChildren: AuthenticatedMainRouteRouteChildren =
  {
    AuthenticatedMainAdminRouteRoute:
      AuthenticatedMainAdminRouteRouteWithChildren,
    AuthenticatedMainSettingsRouteRoute:
      AuthenticatedMainSettingsRouteRouteWithChildren,
    AuthenticatedMainIndexRoute: AuthenticatedMainIndexRoute,
    AuthenticatedMainOrganizationSlugSettingsRouteRoute:
      AuthenticatedMainOrganizationSlugSettingsRouteRouteWithChildren,
    AuthenticatedMainOrganizationSlugIndexRoute:
      AuthenticatedMainOrganizationSlugIndexRoute,
    AuthenticatedMainChatbotIndexRoute: AuthenticatedMainChatbotIndexRoute,
  }

const AuthenticatedMainRouteRouteWithChildren =
  AuthenticatedMainRouteRoute._addFileChildren(
    AuthenticatedMainRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMainRouteRoute: typeof AuthenticatedMainRouteRouteWithChildren
  AuthenticatedCheckoutReturnIndexRoute: typeof AuthenticatedCheckoutReturnIndexRoute
  AuthenticatedChoosePlanIndexRoute: typeof AuthenticatedChoosePlanIndexRoute
  AuthenticatedNewOrganizationIndexRoute: typeof AuthenticatedNewOrganizationIndexRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
  AuthenticatedOrganizationInvitationInvitationIdIndexRoute: typeof AuthenticatedOrganizationInvitationInvitationIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMainRouteRoute: AuthenticatedMainRouteRouteWithChildren,
  AuthenticatedCheckoutReturnIndexRoute: AuthenticatedCheckoutReturnIndexRoute,
  AuthenticatedChoosePlanIndexRoute: AuthenticatedChoosePlanIndexRoute,
  AuthenticatedNewOrganizationIndexRoute:
    AuthenticatedNewOrganizationIndexRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  AuthenticatedOrganizationInvitationInvitationIdIndexRoute:
    AuthenticatedOrganizationInvitationInvitationIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ImageProxySplatRoute: ImageProxySplatRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
