/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedMainRouteRouteImport } from './routes/_authenticated/_main/route'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ImageProxySplatRouteImport } from './routes/image-proxy/$'
import { Route as AuthenticatedMainIndexRouteImport } from './routes/_authenticated/_main/index'
import { Route as AuthenticatedMainOrganizationSlugRouteRouteImport } from './routes/_authenticated/_main/$organizationSlug/route'
import { Route as AuthenticatedMainOrganizationSlugIndexRouteImport } from './routes/_authenticated/_main/$organizationSlug/index'
import { Route as AuthenticatedMainChatbotIndexRouteImport } from './routes/_authenticated/_main/chatbot/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMainRouteRoute = AuthenticatedMainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageProxySplatRoute = ImageProxySplatRouteImport.update({
  id: '/image-proxy/$',
  path: '/image-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMainIndexRoute = AuthenticatedMainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMainRouteRoute,
} as any)
const AuthenticatedMainOrganizationSlugRouteRoute =
  AuthenticatedMainOrganizationSlugRouteRouteImport.update({
    id: '/$organizationSlug',
    path: '/$organizationSlug',
    getParentRoute: () => AuthenticatedMainRouteRoute,
  } as any)
const AuthenticatedMainOrganizationSlugIndexRoute =
  AuthenticatedMainOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMainOrganizationSlugRouteRoute,
  } as any)
const AuthenticatedMainChatbotIndexRoute =
  AuthenticatedMainChatbotIndexRouteImport.update({
    id: '/chatbot/',
    path: '/chatbot/',
    getParentRoute: () => AuthenticatedMainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedMainIndexRoute
  '/api/$': typeof ApiSplatRoute
  '/image-proxy/$': typeof ImageProxySplatRoute
  '/$organizationSlug': typeof AuthenticatedMainOrganizationSlugRouteRouteWithChildren
  '/$organizationSlug/': typeof AuthenticatedMainOrganizationSlugIndexRoute
  '/chatbot/': typeof AuthenticatedMainChatbotIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedMainIndexRoute
  '/api/$': typeof ApiSplatRoute
  '/image-proxy/$': typeof ImageProxySplatRoute
  '/$organizationSlug': typeof AuthenticatedMainOrganizationSlugIndexRoute
  '/chatbot': typeof AuthenticatedMainChatbotIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_main': typeof AuthenticatedMainRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/image-proxy/$': typeof ImageProxySplatRoute
  '/_authenticated/_main/$organizationSlug': typeof AuthenticatedMainOrganizationSlugRouteRouteWithChildren
  '/_authenticated/_main/': typeof AuthenticatedMainIndexRoute
  '/_authenticated/_main/$organizationSlug/': typeof AuthenticatedMainOrganizationSlugIndexRoute
  '/_authenticated/_main/chatbot/': typeof AuthenticatedMainChatbotIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/$'
    | '/image-proxy/$'
    | '/$organizationSlug'
    | '/$organizationSlug/'
    | '/chatbot/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/$' | '/image-proxy/$' | '/$organizationSlug' | '/chatbot'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_main'
    | '/api/$'
    | '/image-proxy/$'
    | '/_authenticated/_main/$organizationSlug'
    | '/_authenticated/_main/'
    | '/_authenticated/_main/$organizationSlug/'
    | '/_authenticated/_main/chatbot/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ImageProxySplatRoute: typeof ImageProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_main': {
      id: '/_authenticated/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedMainRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-proxy/$': {
      id: '/image-proxy/$'
      path: '/image-proxy/$'
      fullPath: '/image-proxy/$'
      preLoaderRoute: typeof ImageProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_main/': {
      id: '/_authenticated/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedMainIndexRouteImport
      parentRoute: typeof AuthenticatedMainRouteRoute
    }
    '/_authenticated/_main/$organizationSlug': {
      id: '/_authenticated/_main/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof AuthenticatedMainOrganizationSlugRouteRouteImport
      parentRoute: typeof AuthenticatedMainRouteRoute
    }
    '/_authenticated/_main/$organizationSlug/': {
      id: '/_authenticated/_main/$organizationSlug/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof AuthenticatedMainOrganizationSlugIndexRouteImport
      parentRoute: typeof AuthenticatedMainOrganizationSlugRouteRoute
    }
    '/_authenticated/_main/chatbot/': {
      id: '/_authenticated/_main/chatbot/'
      path: '/chatbot'
      fullPath: '/chatbot/'
      preLoaderRoute: typeof AuthenticatedMainChatbotIndexRouteImport
      parentRoute: typeof AuthenticatedMainRouteRoute
    }
  }
}

interface AuthenticatedMainOrganizationSlugRouteRouteChildren {
  AuthenticatedMainOrganizationSlugIndexRoute: typeof AuthenticatedMainOrganizationSlugIndexRoute
}

const AuthenticatedMainOrganizationSlugRouteRouteChildren: AuthenticatedMainOrganizationSlugRouteRouteChildren =
  {
    AuthenticatedMainOrganizationSlugIndexRoute:
      AuthenticatedMainOrganizationSlugIndexRoute,
  }

const AuthenticatedMainOrganizationSlugRouteRouteWithChildren =
  AuthenticatedMainOrganizationSlugRouteRoute._addFileChildren(
    AuthenticatedMainOrganizationSlugRouteRouteChildren,
  )

interface AuthenticatedMainRouteRouteChildren {
  AuthenticatedMainOrganizationSlugRouteRoute: typeof AuthenticatedMainOrganizationSlugRouteRouteWithChildren
  AuthenticatedMainIndexRoute: typeof AuthenticatedMainIndexRoute
  AuthenticatedMainChatbotIndexRoute: typeof AuthenticatedMainChatbotIndexRoute
}

const AuthenticatedMainRouteRouteChildren: AuthenticatedMainRouteRouteChildren =
  {
    AuthenticatedMainOrganizationSlugRouteRoute:
      AuthenticatedMainOrganizationSlugRouteRouteWithChildren,
    AuthenticatedMainIndexRoute: AuthenticatedMainIndexRoute,
    AuthenticatedMainChatbotIndexRoute: AuthenticatedMainChatbotIndexRoute,
  }

const AuthenticatedMainRouteRouteWithChildren =
  AuthenticatedMainRouteRoute._addFileChildren(
    AuthenticatedMainRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMainRouteRoute: typeof AuthenticatedMainRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMainRouteRoute: AuthenticatedMainRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ImageProxySplatRoute: ImageProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
