/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as BlogSplatIndexRouteImport } from './routes/blog/$/index'
import { Route as LegalSlugIndexRouteImport } from './routes/legal/$slug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSplatIndexRoute = BlogSplatIndexRouteImport.update({
  id: '/blog/$/',
  path: '/blog/$/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugIndexRoute = LegalSlugIndexRouteImport.update({
  id: '/legal/$slug/',
  path: '/legal/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/': typeof BlogIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/blog/$/': typeof BlogSplatIndexRoute
  '/legal/$slug/': typeof LegalSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog': typeof BlogIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/contact': typeof ContactIndexRoute
  '/blog/$': typeof BlogSplatIndexRoute
  '/legal/$slug': typeof LegalSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/': typeof BlogIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/blog/$/': typeof BlogSplatIndexRoute
  '/legal/$slug/': typeof LegalSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/blog/'
    | '/changelog/'
    | '/contact/'
    | '/blog/$/'
    | '/legal/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/blog'
    | '/changelog'
    | '/contact'
    | '/blog/$'
    | '/legal/$slug'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/blog/'
    | '/changelog/'
    | '/contact/'
    | '/blog/$/'
    | '/legal/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  BlogSplatIndexRoute: typeof BlogSplatIndexRoute
  LegalSlugIndexRoute: typeof LegalSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$/': {
      id: '/blog/$/'
      path: '/blog/$'
      fullPath: '/blog/$/'
      preLoaderRoute: typeof BlogSplatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug/': {
      id: '/legal/$slug/'
      path: '/legal/$slug'
      fullPath: '/legal/$slug/'
      preLoaderRoute: typeof LegalSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogIndexRoute: BlogIndexRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  BlogSplatIndexRoute: BlogSplatIndexRoute,
  LegalSlugIndexRoute: LegalSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
