/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedOrganizationSlugRouteRouteImport } from './routes/_authenticated/$organizationSlug/route'
import { Route as InvitationsInvitationIdRouteImport } from './routes/invitations/$invitationId'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as OrgsNewRouteImport } from './routes/orgs/new'
import { Route as AuthenticatedOrganizationSlugIndexRouteImport } from './routes/_authenticated/$organizationSlug/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedOrganizationSlugSettingsApiKeysIndexRouteImport } from './routes/_authenticated/$organizationSlug/settings/api-keys/index'
import { Route as AuthenticatedOrganizationSlugSettingsMembersIndexRouteImport } from './routes/_authenticated/$organizationSlug/settings/members/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationSlugRouteRoute =
  AuthenticatedOrganizationSlugRouteRouteImport.update({
    id: '/$organizationSlug',
    path: '/$organizationSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const InvitationsInvitationIdRoute = InvitationsInvitationIdRouteImport.update({
  id: '/invitations/$invitationId',
  path: '/invitations/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsNewRoute = OrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizationSlugIndexRoute =
  AuthenticatedOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationSlugRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrganizationSlugSettingsApiKeysIndexRoute =
  AuthenticatedOrganizationSlugSettingsApiKeysIndexRouteImport.update({
    id: '/settings/api-keys/',
    path: '/settings/api-keys/',
    getParentRoute: () => AuthenticatedOrganizationSlugRouteRoute,
  } as any)
const AuthenticatedOrganizationSlugSettingsMembersIndexRoute =
  AuthenticatedOrganizationSlugSettingsMembersIndexRouteImport.update({
    id: '/settings/members/',
    path: '/settings/members/',
    getParentRoute: () => AuthenticatedOrganizationSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/$organizationSlug': typeof AuthenticatedOrganizationSlugRouteRouteWithChildren
  '/invitations/$invitationId': typeof InvitationsInvitationIdRoute
  '/orgs/new': typeof OrgsNewRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$organizationSlug/': typeof AuthenticatedOrganizationSlugIndexRoute
  '/$organizationSlug/settings/api-keys/': typeof AuthenticatedOrganizationSlugSettingsApiKeysIndexRoute
  '/$organizationSlug/settings/members/': typeof AuthenticatedOrganizationSlugSettingsMembersIndexRoute
}
export interface FileRoutesByTo {
  '/invitations/$invitationId': typeof InvitationsInvitationIdRoute
  '/orgs/new': typeof OrgsNewRoute
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$organizationSlug': typeof AuthenticatedOrganizationSlugIndexRoute
  '/$organizationSlug/settings/api-keys': typeof AuthenticatedOrganizationSlugSettingsApiKeysIndexRoute
  '/$organizationSlug/settings/members': typeof AuthenticatedOrganizationSlugSettingsMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/$organizationSlug': typeof AuthenticatedOrganizationSlugRouteRouteWithChildren
  '/invitations/$invitationId': typeof InvitationsInvitationIdRoute
  '/orgs/new': typeof OrgsNewRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/$organizationSlug/': typeof AuthenticatedOrganizationSlugIndexRoute
  '/_authenticated/$organizationSlug/settings/api-keys/': typeof AuthenticatedOrganizationSlugSettingsApiKeysIndexRoute
  '/_authenticated/$organizationSlug/settings/members/': typeof AuthenticatedOrganizationSlugSettingsMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$organizationSlug'
    | '/invitations/$invitationId'
    | '/orgs/new'
    | '/login/'
    | '/api/auth/$'
    | '/$organizationSlug/'
    | '/$organizationSlug/settings/api-keys/'
    | '/$organizationSlug/settings/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/invitations/$invitationId'
    | '/orgs/new'
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/$organizationSlug'
    | '/$organizationSlug/settings/api-keys'
    | '/$organizationSlug/settings/members'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/$organizationSlug'
    | '/invitations/$invitationId'
    | '/orgs/new'
    | '/_authenticated/'
    | '/login/'
    | '/api/auth/$'
    | '/_authenticated/$organizationSlug/'
    | '/_authenticated/$organizationSlug/settings/api-keys/'
    | '/_authenticated/$organizationSlug/settings/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  InvitationsInvitationIdRoute: typeof InvitationsInvitationIdRoute
  OrgsNewRoute: typeof OrgsNewRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$organizationSlug': {
      id: '/_authenticated/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof AuthenticatedOrganizationSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invitations/$invitationId': {
      id: '/invitations/$invitationId'
      path: '/invitations/$invitationId'
      fullPath: '/invitations/$invitationId'
      preLoaderRoute: typeof InvitationsInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/new': {
      id: '/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof OrgsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$organizationSlug/': {
      id: '/_authenticated/$organizationSlug/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof AuthenticatedOrganizationSlugIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationSlugRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$organizationSlug/settings/api-keys/': {
      id: '/_authenticated/$organizationSlug/settings/api-keys/'
      path: '/settings/api-keys'
      fullPath: '/$organizationSlug/settings/api-keys/'
      preLoaderRoute: typeof AuthenticatedOrganizationSlugSettingsApiKeysIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationSlugRouteRoute
    }
    '/_authenticated/$organizationSlug/settings/members/': {
      id: '/_authenticated/$organizationSlug/settings/members/'
      path: '/settings/members'
      fullPath: '/$organizationSlug/settings/members/'
      preLoaderRoute: typeof AuthenticatedOrganizationSlugSettingsMembersIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationSlugRouteRoute
    }
  }
}

interface AuthenticatedOrganizationSlugRouteRouteChildren {
  AuthenticatedOrganizationSlugIndexRoute: typeof AuthenticatedOrganizationSlugIndexRoute
  AuthenticatedOrganizationSlugSettingsApiKeysIndexRoute: typeof AuthenticatedOrganizationSlugSettingsApiKeysIndexRoute
  AuthenticatedOrganizationSlugSettingsMembersIndexRoute: typeof AuthenticatedOrganizationSlugSettingsMembersIndexRoute
}

const AuthenticatedOrganizationSlugRouteRouteChildren: AuthenticatedOrganizationSlugRouteRouteChildren =
  {
    AuthenticatedOrganizationSlugIndexRoute:
      AuthenticatedOrganizationSlugIndexRoute,
    AuthenticatedOrganizationSlugSettingsApiKeysIndexRoute:
      AuthenticatedOrganizationSlugSettingsApiKeysIndexRoute,
    AuthenticatedOrganizationSlugSettingsMembersIndexRoute:
      AuthenticatedOrganizationSlugSettingsMembersIndexRoute,
  }

const AuthenticatedOrganizationSlugRouteRouteWithChildren =
  AuthenticatedOrganizationSlugRouteRoute._addFileChildren(
    AuthenticatedOrganizationSlugRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrganizationSlugRouteRoute: typeof AuthenticatedOrganizationSlugRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrganizationSlugRouteRoute:
    AuthenticatedOrganizationSlugRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  InvitationsInvitationIdRoute: InvitationsInvitationIdRoute,
  OrgsNewRoute: OrgsNewRoute,
  LoginIndexRoute: LoginIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
